; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

<<<<<<< HEAD
[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps = miguelbalboa/MFRC522@^1.4.11
board_build.partitions = huge_app.csv
build_flags = 
	-DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
; --- CONFIGURACIÓN PARA EL LECTOR ---
[env:lector_ilumetria]
; Hereda todo lo de [env] y añade el filtro
build_src_filter = +<reader_main.cpp> -<writer_main.cpp>

; --- CONFIGURACIÓN PARA EL ESCRITOR ---
[env:escritor_ilumetria]
; Hereda todo lo de [env] y añade el filtro
build_src_filter = -<reader_main.cpp> +<writer_main.cpp>
=======
[env:esp32s3cam]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags = 
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=5
board_build.arduino.memory_type = qio_qspi
board_build.f_cpu = 240000000L
monitor_speed = 115200
<<<<<<< HEAD
lib_deps = miguelbalboa/MFRC522@^1.4.11	q
>>>>>>> 31c853d (Creación de módulo para control de lectura/escriitura NFC)
=======
lib_deps = miguelbalboa/MFRC522@^1.4.12
>>>>>>> 9b6a03a (ajustes a platformio ini con instalación de librería)
