; PlatformIO Project Configuration File
;
; Módulo UHF RFID Reader para ESP32-C3
; Protocolo: ISO 18000-6C (EPC Gen2)
; Comunicación: UART Serial
; Lector: R16 UHF (902-928 MHz)

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Opciones de build
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3

; Monitor filters
monitor_filters = 
    esp32_exception_decoder
    default
